slam_toolbox:
  ros__parameters:
    use_sim_time: true
    mode: mapping
    map_update_interval: 2.0
    resolution: 0.05
    max_laser_range: 3.5
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    base_frame: base_link
    odom_frame: odom
    map_frame: map
    scan_topic: /scan
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1
